In [1]:
import sklearn as sk
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("ProcessedData.csv")
y,x = dataset.iloc[:,-1], dataset.iloc[:,0:4]


# x -> label
# y -> data

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
#x_train, x_test, y_train, y_test = np.array(x_train), np.array(x_test), np.array(y_train), np.array(y_test)

In [3]:
# Normalizing
ss_train = StandardScaler()
ss_test = StandardScaler()
x_train = ss_train.fit_transform(x_train)
x_test = ss_test.fit_transform(x_test)

print(x_train)

[[-0.30911276  0.0051813  -0.00725876  0.19694303]
 [-1.62666188  1.67994418  2.96398535  3.69765647]
 [-0.25995048  1.67994418 -0.66101241 -0.50004481]
 ...
 [ 1.08709602  0.42387202 -1.14038855 -1.11734323]
 [ 1.0674311  -0.97176372  1.29222631  0.7839384 ]
 [ 0.85111707  0.56343559 -0.59943073 -0.46068515]]


In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [28]:

model.fit(x_train, y_train)

predictions = model.predict(x_test)
model.score(x_test,y_test)

0.8436940737237995